import { readFile, writeFile } from 'node:fs/promises';

const input = process.argv[2];
if (!input) throw new Error('Usage: node scripts/build-data.mjs path/to/pokemon-species.json');
const raw = JSON.parse(await readFile(input, 'utf8'));
const title = id => id.split('-').map(w => ({mr:'Mr.',mime:'Mime',jr:'Jr.',type:'Type:',nidoran:'Nidoran'}[w] || w[0].toUpperCase()+w.slice(1))).join(' ')
  .replace('Nidoran F','Nidoran ♀').replace('Nidoran M','Nidoran ♂').replace('Farfetchd','Farfetch’d').replace('Sirfetchd','Sirfetch’d');
const species = raw.results.map((p, i) => ({ id:p.name, name:title(p.name), dex:i+1 }));
const P = (id, name, imageId=id) => ({id,name,imageId});

const forms = [
  ['Kanto Forms', [P('rattata','Rattata'),P('rattata-alola','Alolan Rattata'),P('raticate','Raticate'),P('raticate-alola','Alolan Raticate'),P('raichu','Raichu'),P('raichu-alola','Alolan Raichu'),P('sandshrew','Sandshrew'),P('sandshrew-alola','Alolan Sandshrew'),P('sandslash','Sandslash'),P('sandslash-alola','Alolan Sandslash'),P('vulpix','Vulpix'),P('vulpix-alola','Alolan Vulpix'),P('ninetales','Ninetales'),P('ninetales-alola','Alolan Ninetales'),P('diglett','Diglett'),P('diglett-alola','Alolan Diglett'),P('dugtrio','Dugtrio'),P('dugtrio-alola','Alolan Dugtrio'),P('meowth','Meowth'),P('meowth-alola','Alolan Meowth'),P('meowth-galar','Galarian Meowth'),P('persian','Persian'),P('persian-alola','Alolan Persian'),P('geodude','Geodude'),P('geodude-alola','Alolan Geodude'),P('graveler','Graveler'),P('graveler-alola','Alolan Graveler'),P('golem','Golem'),P('golem-alola','Alolan Golem')]],
  ['Kanto Forms II', [P('ponyta','Ponyta'),P('ponyta-galar','Galarian Ponyta'),P('rapidash','Rapidash'),P('rapidash-galar','Galarian Rapidash'),P('slowpoke','Slowpoke'),P('slowpoke-galar','Galarian Slowpoke'),P('slowbro','Slowbro'),P('slowbro-galar','Galarian Slowbro'),P('farfetchd','Farfetch’d'),P('farfetchd-galar','Galarian Farfetch’d'),P('grimer','Grimer'),P('grimer-alola','Alolan Grimer'),P('muk','Muk'),P('muk-alola','Alolan Muk'),P('exeggutor','Exeggutor'),P('exeggutor-alola','Alolan Exeggutor'),P('marowak','Marowak'),P('marowak-alola','Alolan Marowak'),P('weezing','Weezing'),P('weezing-galar','Galarian Weezing'),P('mr-mime','Mr. Mime'),P('mr-mime-galar','Galarian Mr. Mime'),P('tauros','Tauros'),P('tauros-paldea-combat-breed','Paldean Tauros: Combat'),P('tauros-paldea-blaze-breed','Paldean Tauros: Blaze'),P('tauros-paldea-aqua-breed','Paldean Tauros: Aqua'),P('articuno','Articuno'),P('articuno-galar','Galarian Articuno'),P('zapdos','Zapdos'),P('zapdos-galar','Galarian Zapdos')]],
  ['Johto & Hoenn Forms', [P('moltres','Moltres'),P('moltres-galar','Galarian Moltres'),P('typhlosion','Typhlosion'),P('typhlosion-hisui','Hisuian Typhlosion'),P('wooper','Wooper'),P('wooper-paldea','Paldean Wooper'),P('slowking','Slowking'),P('slowking-galar','Galarian Slowking'),P('qwilfish','Qwilfish'),P('qwilfish-hisui','Hisuian Qwilfish'),P('sneasel','Sneasel'),P('sneasel-hisui','Hisuian Sneasel'),P('corsola','Corsola'),P('corsola-galar','Galarian Corsola'),P('zigzagoon','Zigzagoon'),P('zigzagoon-galar','Galarian Zigzagoon'),P('linoone','Linoone'),P('linoone-galar','Galarian Linoone'),P('deoxys-normal','Deoxys Normal'),P('deoxys-attack','Deoxys Attack'),P('deoxys-defense','Deoxys Defense'),P('deoxys-speed','Deoxys Speed')]],
  ['Sinnoh Forms', [P('burmy','Burmy Plant'),P('burmy-sandy','Burmy Sandy'),P('burmy-trash','Burmy Trash'),P('wormadam-plant','Wormadam Plant'),P('wormadam-sandy','Wormadam Sandy'),P('wormadam-trash','Wormadam Trash'),P('cherrim','Cherrim Overcast'),P('cherrim-sunshine','Cherrim Sunshine'),P('shellos-west','Shellos West'),P('shellos-east','Shellos East'),P('gastrodon-west','Gastrodon West'),P('gastrodon-east','Gastrodon East'),P('rotom','Rotom'),P('rotom-heat','Heat Rotom'),P('rotom-wash','Wash Rotom'),P('rotom-frost','Frost Rotom'),P('rotom-fan','Fan Rotom'),P('rotom-mow','Mow Rotom'),P('giratina-altered','Giratina Altered'),P('giratina-origin','Giratina Origin'),P('shaymin-land','Shaymin Land'),P('shaymin-sky','Shaymin Sky')]],
  ['Unova Forms', [P('basculin-red-striped','Basculin Red'),P('basculin-blue-striped','Basculin Blue'),P('basculin-white-striped','Basculin White'),P('deerling-spring','Deerling Spring'),P('deerling-summer','Deerling Summer'),P('deerling-autumn','Deerling Autumn'),P('deerling-winter','Deerling Winter'),P('sawsbuck-spring','Sawsbuck Spring'),P('sawsbuck-summer','Sawsbuck Summer'),P('sawsbuck-autumn','Sawsbuck Autumn'),P('sawsbuck-winter','Sawsbuck Winter'),P('tornadus-incarnate','Tornadus Incarnate'),P('tornadus-therian','Tornadus Therian'),P('thundurus-incarnate','Thundurus Incarnate'),P('thundurus-therian','Thundurus Therian'),P('landorus-incarnate','Landorus Incarnate'),P('landorus-therian','Landorus Therian'),P('keldeo-ordinary','Keldeo Ordinary'),P('keldeo-resolute','Keldeo Resolute'),P('meloetta-aria','Meloetta Aria'),P('meloetta-pirouette','Meloetta Pirouette')]],
  ['Kalos Forms', [P('flabebe-red','Flabébé Red'),P('flabebe-yellow','Flabébé Yellow'),P('flabebe-orange','Flabébé Orange'),P('flabebe-blue','Flabébé Blue'),P('flabebe-white','Flabébé White'),P('floette-red','Floette Red'),P('floette-yellow','Floette Yellow'),P('floette-orange','Floette Orange'),P('floette-blue','Floette Blue'),P('floette-white','Floette White'),P('florges-red','Florges Red'),P('florges-yellow','Florges Yellow'),P('florges-orange','Florges Orange'),P('florges-blue','Florges Blue'),P('florges-white','Florges White'),P('furfrou-natural','Furfrou Natural'),P('furfrou-heart','Furfrou Heart'),P('furfrou-star','Furfrou Star'),P('furfrou-diamond','Furfrou Diamond'),P('furfrou-debutante','Furfrou Debutante'),P('furfrou-matron','Furfrou Matron'),P('furfrou-dandy','Furfrou Dandy'),P('furfrou-la-reine','Furfrou La Reine'),P('furfrou-kabuki','Furfrou Kabuki'),P('furfrou-pharaoh','Furfrou Pharaoh'),P('pumpkaboo-small','Pumpkaboo Small'),P('pumpkaboo-average','Pumpkaboo Average'),P('pumpkaboo-large','Pumpkaboo Large'),P('pumpkaboo-super','Pumpkaboo Super')]],
  ['Alola Forms', [P('oricorio-baile','Oricorio Baile'),P('oricorio-pom-pom','Oricorio Pom-Pom'),P('oricorio-pau','Oricorio Pa’u'),P('oricorio-sensu','Oricorio Sensu'),P('lycanroc-midday','Lycanroc Midday'),P('lycanroc-midnight','Lycanroc Midnight'),P('lycanroc-dusk','Lycanroc Dusk'),P('wishiwashi-solo','Wishiwashi Solo'),P('wishiwashi-school','Wishiwashi School'),P('minior-red-meteor','Minior Meteor'),P('minior-red','Minior Red Core'),P('minior-orange','Minior Orange Core'),P('minior-yellow','Minior Yellow Core'),P('minior-green','Minior Green Core'),P('minior-blue','Minior Blue Core'),P('minior-indigo','Minior Indigo Core'),P('minior-violet','Minior Violet Core'),P('necrozma','Necrozma'),P('necrozma-dusk','Dusk Mane Necrozma'),P('necrozma-dawn','Dawn Wings Necrozma'),P('necrozma-ultra','Ultra Necrozma')]],
  ['Galar Forms', [P('corsola-galar','Galarian Corsola'),P('cursola','Cursola'),P('farfetchd-galar','Galarian Farfetch’d'),P('sirfetchd','Sirfetch’d'),P('meowth-galar','Galarian Meowth'),P('perrserker','Perrserker'),P('mr-mime-galar','Galarian Mr. Mime'),P('mr-rime','Mr. Rime'),P('yamask','Yamask'),P('yamask-galar','Galarian Yamask'),P('stunfisk','Stunfisk'),P('stunfisk-galar','Galarian Stunfisk'),P('darumaka','Darumaka'),P('darumaka-galar','Galarian Darumaka'),P('darmanitan-standard','Darmanitan'),P('darmanitan-galar-standard','Galarian Darmanitan'),P('toxtricity-amped','Toxtricity Amped'),P('toxtricity-low-key','Toxtricity Low Key'),P('sinistea','Sinistea Phony'),P('sinistea-antique','Sinistea Antique'),P('polteageist','Polteageist Phony'),P('polteageist-antique','Polteageist Antique'),P('urshifu-single-strike','Urshifu Single Strike'),P('urshifu-rapid-strike','Urshifu Rapid Strike')]],
  ['Hisui Forms', [P('growlithe-hisui','Hisuian Growlithe'),P('arcanine-hisui','Hisuian Arcanine'),P('voltorb-hisui','Hisuian Voltorb'),P('electrode-hisui','Hisuian Electrode'),P('samurott-hisui','Hisuian Samurott'),P('lilligant-hisui','Hisuian Lilligant'),P('zorua-hisui','Hisuian Zorua'),P('zoroark-hisui','Hisuian Zoroark'),P('braviary-hisui','Hisuian Braviary'),P('sliggoo-hisui','Hisuian Sliggoo'),P('goodra-hisui','Hisuian Goodra'),P('avalugg-hisui','Hisuian Avalugg'),P('decidueye-hisui','Hisuian Decidueye'),P('dialga-origin','Origin Dialga'),P('palkia-origin','Origin Palkia'),P('enamorus-incarnate','Enamorus Incarnate'),P('enamorus-therian','Enamorus Therian')]],
  ['Paldea & Convergent Forms', [P('palafin-zero','Palafin Zero'),P('palafin-hero','Palafin Hero'),P('maushold-family-of-four','Maushold Family of Four'),P('maushold-family-of-three','Maushold Family of Three'),P('squawkabilly-green-plumage','Squawkabilly Green'),P('squawkabilly-blue-plumage','Squawkabilly Blue'),P('squawkabilly-yellow-plumage','Squawkabilly Yellow'),P('squawkabilly-white-plumage','Squawkabilly White'),P('tatsugiri-curly','Tatsugiri Curly'),P('tatsugiri-droopy','Tatsugiri Droopy'),P('tatsugiri-stretchy','Tatsugiri Stretchy'),P('dudunsparce-two-segment','Dudunsparce Two Segment'),P('dudunsparce-three-segment','Dudunsparce Three Segment'),P('gimmighoul','Gimmighoul Chest'),P('gimmighoul-roaming','Gimmighoul Roaming'),P('poltchageist','Poltchageist Counterfeit'),P('poltchageist-artisan','Poltchageist Artisan'),P('sinistcha','Sinistcha Unremarkable'),P('sinistcha-masterpiece','Sinistcha Masterpiece'),P('tentacool','Tentacool'),P('toedscool','Toedscool'),P('tentacruel','Tentacruel'),P('toedscruel','Toedscruel'),P('diglett','Diglett'),P('wiglett','Wiglett'),P('dugtrio','Dugtrio'),P('wugtrio','Wugtrio')]]
];
const boxes = [];
for (let i=0;i<species.length;i+=30) boxes.push({id:`dex-${i+1}-${Math.min(i+30,species.length)}`,title:`${i+1}–${Math.min(i+30,species.length)}`,pokemon:species.slice(i,i+30)});
forms.forEach(([name,pokemon],i) => boxes.push({id:`forms-${i+1}`,title:name,pokemon}));
await writeFile('data/pokemon.js', `// Generated Pokémon and box definitions. Edit freely; keep box and form IDs stable once tracking.\nwindow.POKEMON_DATA = ${JSON.stringify({boxes},null,2)};\n`);
console.log(`Wrote ${boxes.length} boxes (${species.length} National Dex species + ${forms.reduce((n,f)=>n+f[1].length,0)} form slots).`);
